sonar.projectKey=frappe-lms
sonar.projectName=Frappe LMS
sonar.projectVersion=1.0.0

sonar.sources=lms,frontend

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/cypress/**,dist/**,**/public/frontend/**,**/*.spec.js,**/*.test.js,**/*.json,**/*.lock,**/*.png,**/*.jpg,**/*.jpeg,**/*.gif,**/*.svg,**/*.ico,**/*.mp4,**/*.zip,**/*.pdf

sonar.tests=lms
sonar.test.inclusions=**/test_*.py,**/*.spec.js,**/*.test.js
sonar.python.version=3.10
sonar.python.coverage.reportPaths=coverage.xml
sonar.qualitygate.wait=true