sonar.projectKey=frappe-lms
sonar.projectName=Frappe LMS
sonar.projectVersion=1.0.0

sonar.sources=lms,frontend,frappe-ui

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/cypress/**,dist/**,**/public/frontend/**,**/*.spec.js,**/*.test.js,**/*.json,**/*.lock

sonar.python.version=3.10