from .test_import_export import TestImportExportIntegration
from .test_permissions import TestPermissionsIntegration
from .test_batch import TestBatchIntegration
from .test_enrollment import TestEnrollmentProgress
from .test_badges import TestBadgeEnrollment
from .test_certificates import TestCertificateCompletion
from .test_course_deletion import TestCourseDeletion
from .test_evaluations import TestQuizValidation
