name: CI/CD Pipeline
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests-suite:
    name: Server Tests Suite
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    services:
      redis-cache:
        image: redis:alpine
        ports:
          - 13000:6379

      redis-queue:
        image: redis:alpine
        ports:
          - 11000:6379

      redis-socketio:
        image: redis:alpine
        ports:
          - 12000:6379

      mariadb:
        image: anandology/mariadb-utf8mb4:10.3
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          check-latest: true

      - name: Setup cache for Bench
        uses: actions/cache@v4
        with:
          path: ~/bench-cache
          key: ${{ runner.os }}-bench

      - name: Install Bench
        run: |
          pip3 install frappe-bench
          which bench

      - name: Initialize Bench
        run: |
          if [ -f ~/bench-cache/bench.tgz ]
          then
            (cd && tar xzf ~/bench-cache/bench.tgz)
          else
            bench init ~/frappe-bench --skip-redis-config-generation --skip-assets --python "$(which python)"
            mkdir -p ~/bench-cache
            (cd && tar czf ~/bench-cache/bench.tgz frappe-bench)
          fi

      - name: Add payments app to Bench
        working-directory: /home/runner/frappe-bench
        run: bench get-app https://github.com/frappe/payments

      - name: Add LMS app to Bench
        working-directory: /home/runner/frappe-bench
        run: bench get-app lms $GITHUB_WORKSPACE

      - name: Create Bench site
        working-directory: /home/runner/frappe-bench
        run: bench new-site --mariadb-root-password root --admin-password admin frappe.local

      - name: Install LMS app
        working-directory: /home/runner/frappe-bench
        run: bench --site frappe.local install-app lms

      - name: Setup requirements
        working-directory: /home/runner/frappe-bench
        run: bench setup requirements --dev

      - name: Block endpoints
        working-directory: /home/runner/frappe-bench
        run: bench --site frappe.local set-config block_endpoints 1

      - name: Allow tests
        working-directory: /home/runner/frappe-bench
        run: bench --site frappe.local set-config allow_tests true

      - name: Build assets
        working-directory: /home/runner/frappe-bench
        run: bench --site frappe.local build

      - name: Run unit tests
        working-directory: /home/runner/frappe-bench
        run: bench --site frappe.local run-tests --app lms --coverage

      - name: Run integration tests
        working-directory: /home/runner/frappe-bench
        env:
          RUN_INTEGRATION_TESTS: "1"
        run: bench --site frappe.local run-tests --app lms --module lms.lms.tests.integration

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-coverage
          path: /home/runner/frappe-bench/sites/coverage.xml

  coverage:
    name: Coverage Wrap Up
    needs: tests-suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: server-coverage

      - name: Upload coverage data to Codecov
        uses: codecov/codecov-action@v6.0.2
        with:
          name: Server
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

  sonar:
    name: SonarQube Analysis
    needs: tests-suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: server-coverage
          path: .

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v2
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    name: Build & Push Docker Image
    needs: [tests-suite, sonar]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout Entire Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Image Tag
        run: |
          echo "IMAGE_TAG=stable" >> $GITHUB_ENV
          echo "REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ env.REPO_LOWER }}:${{ github.ref_name }}
            ghcr.io/${{ env.REPO_LOWER }}:${{ env.IMAGE_TAG }}

  deploy:
    name: Trigger Deploy
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Call Dokploy Webhook
        run: |
          curl -X POST "${{ secrets.DOKPLOY_WEBHOOK_URL }}"